import { useState } from 'react'
import { Button, ConfirmDialog, DataToolbar, EmptyState, ErrorState, Input, LoadingState, Modal, PageHeader, Panel, Select, Table, Textarea } from '../../../components/ui'
import { DocumentTitle } from '../../../routes/pages'
import { useAuth } from '../../auth/auth-context'
import { useAdminAnnouncements, useCreateAnnouncement, useDeleteAnnouncement, useUpdateAnnouncement } from '../hooks'
import type { Announcement } from '../api/announcement.api'

export function AdminAnnouncementsPage() {
  const auth = useAuth(); const list = useAdminAnnouncements(); const create = useCreateAnnouncement(); const update = useUpdateAnnouncement(); const remove = useDeleteAnnouncement()
  const [modalOpen, setModalOpen] = useState(false); const [editing, setEditing] = useState<Announcement | null>(null); const [deleting, setDeleting] = useState<string | null>(null); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [active, setActive] = useState('true'); const [search, setSearch] = useState(''); const [errors, setErrors] = useState<{ title?: string; content?: string }>({})
  const open = (item?: Announcement) => { setModalOpen(true); setEditing(item ?? null); setTitle(item?.title ?? ''); setContent(item?.content ?? ''); setActive(item?.isActive === false ? 'false' : 'true'); setErrors({}) }
  const source = Array.isArray(list.data) ? list.data : ((list.data as unknown as { items?: Announcement[] } | undefined)?.items ?? [])
  const items = source.filter((item) => `${item.title} ${item.content}`.toLocaleLowerCase('tr-TR').includes(search.toLocaleLowerCase('tr-TR')) && (active === '' || String(item.isActive !== false) === active))
  const save = async () => { const next = { title: title.trim() ? undefined : 'Bu alan zorunludur', content: content.trim() ? undefined : 'Bu alan zorunludur' }; setErrors(next); if (next.title || next.content) return; const payload = { title: title.trim(), content: content.trim(), targetRoles: ['STUDENT', 'ACADEMIC', 'ADMINISTRATIVE'], departmentId: auth.user?.role === 'ACADEMIC' ? auth.user.departmentId ?? null : null, expiresAt: null, isActive: active === 'true' }; if (editing) await update.mutateAsync({ id: editing.id, payload }); else await create.mutateAsync(payload); setEditing(null); setModalOpen(false) }
  const valid = Boolean(title.trim() && content.trim())
  return <><DocumentTitle title="Duyurular" /><PageHeader title="Duyurular" description="Kurum duyurularını modal formlarla yayınlayın." backHref="/dashboard" backLabel="Panele dön" actions={<Button onClick={() => open()}>Yeni Duyuru Ekle</Button>} /><Panel><DataToolbar search={{ value: search, onChange: setSearch, placeholder: 'Başlık veya içerik ara' }} filters={<Select label="Durum" value={active} onChange={(e) => setActive(e.target.value)} options={[{ value: '', label: 'Tümü' }, { value: 'true', label: 'Aktif' }, { value: 'false', label: 'Taslak' }]} />} />{list.isLoading ? <LoadingState label="Duyurular yükleniyor" /> : list.isError ? <ErrorState title="Duyurular alınamadı" message="Liste yüklenemedi." onRetry={() => void list.refetch()} /> : items.length === 0 ? <EmptyState title="Kayıt bulunamadı" message="Yeni duyuru eklemek için sağ üstteki düğmeyi kullanın." /> : <Table caption="Duyurular" columns={[{ key: 'title', header: 'Başlık' }, { key: 'content', header: 'İçerik' }, { key: 'isActive', header: 'Durum', render: (item) => item.isActive === false ? 'Taslak' : 'Aktif' }, { key: 'actions', header: 'İşlemler', render: (item) => <div className="flex gap-2"><Button variant="secondary" onClick={() => open(item)}>Düzenle</Button><Button variant="danger" onClick={() => setDeleting(item.id)}>Sil</Button></div> }]} data={items} rowKey={(item) => item.id} />}</Panel><Modal open={modalOpen} title={editing ? 'Duyuruyu düzenle' : 'Yeni duyuru'} onClose={() => { setModalOpen(false); setEditing(null); setErrors({}) }}><div className="grid gap-3"><Input label="Başlık" value={title} error={errors.title} onChange={(e) => { setTitle(e.target.value); setErrors({ ...errors, title: undefined }) }} /><Textarea label="İçerik" value={content} error={errors.content} onChange={(e) => { setContent(e.target.value); setErrors({ ...errors, content: undefined }) }} /><Select label="Durum" value={active} onChange={(e) => setActive(e.target.value)} options={[{ value: 'true', label: 'Aktif' }, { value: 'false', label: 'Taslak' }]} /><Button loading={create.isPending || update.isPending} disabled={!valid || create.isPending || update.isPending} onClick={() => void save()}>Kaydet</Button></div></Modal><ConfirmDialog open={Boolean(deleting)} title="Duyuruyu sil" description="Bu duyuru kalıcı olarak silinecek." confirmLabel="Sil" variant="danger" loading={remove.isPending} onCancel={() => setDeleting(null)} onConfirm={() => deleting ? void remove.mutateAsync(deleting).then(() => setDeleting(null)) : undefined} /></>
}
