import { useQuery } from '@tanstack/react-query'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { ArrowLeft, Eye } from 'lucide-react'
import { Badge, DataToolbar, EmptyState, ErrorState, LoadingState, PageHeader, Panel, Pagination, Select, Table } from '../../../components/ui'
import { api } from '../../../lib/api'
import { DocumentTitle } from '../../../routes/pages'

type AdminInternship = { id: string; studentName: string; studentNumber: string | null; departmentName: string; companyName: string; startDate: string; endDate: string; status: string; employerGrade: string; readOnly: true }
const labels: Record<string, string> = { DRAFT: 'Öğrenci Başvuru Taslağı', PENDING_EMPLOYER: 'Firma Kabul Belgesi İncelemesi', PENDING_COMMISSION: 'Bölüm Ön Kontrol / Komisyon Onayı Bekleyen', APPROVED_PENDING_SGK: 'SGK Giriş Onayı Bekleyen', ONGOING: 'Aktif Devam Eden Staj', ACTIVE: 'Aktif Devam Eden Staj', EVALUATION: 'Staj Defteri Değerlendirme', GRADED: 'Notlandırıldı', COMPLETED: 'Arşivlendi / Tamamlandı', REVISION: 'Revizyon Bekleyen', REJECTED: 'Reddedildi' }

export function AdminInternshipsPage() {
  const [params, setParams] = useSearchParams(); const status = params.get('status') ?? ''; const term = params.get('term') ?? ''; const page = Number(params.get('page') ?? 1)
  const query = useQuery({ queryKey: ['admin', 'internships', { status, term, page }], queryFn: async () => (await api.get<{ items: AdminInternship[]; total: number }>('/admin/internships', { params: { status: status || undefined, term: term || undefined, page, pageSize: 20 } })).data })
  const update = (changes: Record<string, string | null>) => { const next = new URLSearchParams(params); Object.entries(changes).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); setParams(next) }
  const rows = query.data?.items ?? []
  return <><DocumentTitle title="Yönetici staj görünümü" /><PageHeader title="Staj kayıtları" description="Yönetici görünümü — salt okunur erişim." backHref="/dashboard" backLabel="Panele dön" /><Panel><DataToolbar search={{ value: '', onChange: () => undefined, placeholder: 'Kayıtlar filtreleri URL üzerinden yönetilir' }} filters={<div className="flex items-end gap-2"><Select label="Durum" value={status} onChange={(event) => update({ status: event.target.value || null, page: '1' })} options={[{ value: '', label: 'Tüm durumlar' }, ...Object.entries(labels).map(([value, label]) => ({ value, label }))]} /><button type="button" className="min-h-10 rounded border border-gray-300 bg-white px-3 text-sm font-semibold text-navy" onClick={() => update({ term: term ? null : 'current', page: '1' })}>{term ? 'Tüm Dönemler' : 'Aktif Dönem'}</button></div>} />{term ? <div className="mb-3 inline-flex rounded-full border border-blue-200 bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-800">Dönem: Aktif dönem</div> : null}{query.isFetching && !query.isLoading ? <p className="mb-2 text-xs text-gray-500">Güncelleniyor…</p> : null}{query.isLoading ? <LoadingState label="Staj kayıtları yükleniyor" /> : query.isError ? <ErrorState title="Staj kayıtları alınamadı" message="Salt okunur kayıtlar yüklenirken bir sorun oluştu." onRetry={() => void query.refetch()} /> : rows.length === 0 ? <EmptyState title="Kayıt bulunamadı" message="Seçilen filtrelerde görüntülenecek staj yok." /> : <><Table caption="Yönetici staj kayıtları" columns={[{ key: 'studentName', header: 'Öğrenci', render: (row) => <span>{row.studentName}<small className="ml-1 text-gray-500">{row.studentNumber ?? '—'}</small></span> }, { key: 'departmentName', header: 'Bölüm' }, { key: 'companyName', header: 'Firma' }, { key: 'startDate', header: 'Tarih', render: (row) => `${row.startDate} — ${row.endDate}` }, { key: 'status', header: 'Durum', render: (row) => <Badge variant="info">{labels[row.status] ?? row.status}</Badge> }, { key: 'actions', header: 'Görünüm', render: (row) => <Link className="inline-flex items-center gap-1 font-semibold text-navy underline" to={`/admin/internships/${row.id}`}><Eye className="h-4 w-4" aria-hidden="true" />Detay</Link> }]} data={rows} rowKey={(row) => row.id} /><Pagination className="mt-4 justify-end" page={page} totalPages={Math.max(1, Math.ceil((query.data?.total ?? 0) / 20))} onPageChange={(next) => update({ page: String(next) })} /></>}</Panel></>
}

export function AdminInternshipDetailPage() { const { id } = useParams(); const query = useQuery({ queryKey: ['admin', 'internships', id], queryFn: async () => (await api.get<AdminInternship>(`/admin/internships/${id}`)).data, enabled: Boolean(id) }); return <><DocumentTitle title="Yönetici staj detayı" /><PageHeader title="Staj detayı" description="Yönetici görünümü — salt okunur erişim." backHref="/admin/internships" backLabel="Staj kayıtlarına dön" />{query.isLoading ? <LoadingState label="Staj detayı yükleniyor" /> : query.isError || !query.data ? <ErrorState title="Staj detayı alınamadı" message="Kayıt bulunamadı veya görüntülenemiyor." onRetry={() => void query.refetch()} /> : <Panel title={`${query.data.studentName} · ${query.data.studentNumber ?? 'Öğrenci numarası yok'}`}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['Bölüm', query.data.departmentName], ['Firma', query.data.companyName], ['Başlangıç', query.data.startDate], ['Bitiş', query.data.endDate], ['Durum', labels[query.data.status] ?? query.data.status], ['Akademik not', query.data.employerGrade]].map(([label, value]) => <div key={label} className="border-b border-gray-100 pb-2"><p className="text-xs uppercase tracking-wide text-gray-500">{label}</p><p className="mt-1 font-semibold text-navy">{value}</p></div>)}</div><div className="mt-5 flex items-center gap-2 rounded border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900"><ArrowLeft className="h-4 w-4" aria-hidden="true" />Günlük kayıtlar, belgeler ve işveren değerlendirmesi yönetici rolüne kapalıdır.</div></Panel>}</> }
