export enum InternshipStatus {
  DRAFT = 'DRAFT',
  APPLIED = 'APPLIED',
  REVISION = 'REVISION',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ONGOING = 'ONGOING',
  EVALUATION = 'EVALUATION',
  GRADED = 'GRADED',
  COMPLETED = 'COMPLETED',
  WITHDRAWN = 'WITHDRAWN',
}
