import { useQuery } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Button, ErrorState, LoadingState, PageHeader, Panel, Select, Table, Textarea, Input } from '../../../components/ui'
import { normalizeApiError, publicApi } from '../../../lib/api'
import { DocumentTitle } from '../../../routes/pages'
import { employerEvaluationCriteria } from '../../academic/components/EmployerEvaluationPanel'

interface EvaluationContext { valid: true; internshipId: string; studentName: string; companyName: string; startDate: string; endDate: string }
interface DailyLog { logDate: string; content: string }

export function EmployerEvaluationPage() {
  const { token = '' } = useParams<{ token: string }>(); const [employerName, setEmployerName] = useState(''); const [comments, setComments] = useState(''); const [grades, setGrades] = useState<Record<string, string>>({}); const [submitState, setSubmitState] = useState<'idle' | 'loading' | 'success' | 'error'>('idle'); const [submitError, setSubmitError] = useState(''); const [signedAt, setSignedAt] = useState<string | null>(null)
  const context = useQuery({ queryKey: ['public-employer-evaluation', token], queryFn: async () => (await publicApi.get<EvaluationContext>('/employer-evaluation/validate', { params: { token } })).data, enabled: Boolean(token) })
  const logs = useQuery({ queryKey: ['public-employer-daily-logs', token], queryFn: async () => (await publicApi.get<DailyLog[]>('/employer-evaluation/daily-logs', { params: { token } })).data, enabled: Boolean(token) })
  const complete = useMemo(() => employerEvaluationCriteria.every(([key]) => Boolean(grades[key])), [grades]);
  async function submit() { setSubmitState('loading'); try { const response = await publicApi.post<{ employerLogsApprovedAt?: string; submittedAt?: string }>('/employer-evaluation/submit', { token, employerName: employerName.trim(), grades, comments: comments || null }); setSignedAt(response.data.employerLogsApprovedAt ?? response.data.submittedAt ?? new Date().toISOString()); setSubmitState('success') } catch (error) { setSubmitError(normalizeApiError(error).message); setSubmitState('error') } }
  if (context.isLoading) return <main className="mx-auto max-w-3xl p-6"><DocumentTitle title="İşveren değerlendirmesi" /><PageHeader title="İşveren değerlendirmesi" description="Değerlendirme bağlantısı doğrulanıyor." /><LoadingState label="Değerlendirme bağlantısı doğrulanıyor" /></main>
  if (context.isError || !context.data) return <main className="mx-auto max-w-3xl p-6"><DocumentTitle title="İşveren değerlendirmesi" /><PageHeader title="İşveren değerlendirmesi" description="İşveren tokenı ile güvenli değerlendirme." /><ErrorState title="Bağlantı geçersiz" message={normalizeApiError(context.error).message} /></main>
  if (submitState === 'success') return <main className="mx-auto flex min-h-screen max-w-3xl items-center p-6"><DocumentTitle title="Değerlendirme tamamlandı" /><Panel><PageHeader title="Değerlendirme alındı" description="Günlük kayıtlar işveren tarafından dijital olarak onaylandı." />{signedAt ? <p className="mt-3 rounded border-l-4 border-gold bg-gold/10 p-3 text-sm font-semibold text-navy">Dijital imza zamanı: {new Date(signedAt).toLocaleString('tr-TR')}</p> : null}</Panel></main>
  return <main className="mx-auto max-w-3xl p-6"><DocumentTitle title="İşveren değerlendirmesi" /><PageHeader title="İşveren değerlendirmesi" description={`${context.data.studentName} · ${context.data.companyName} · ${context.data.startDate} — ${context.data.endDate}`} /><div className="mb-4 rounded border-l-4 border-gold bg-gold/10 p-4 text-sm text-navy"><strong>Önemli:</strong> Değerlendirmeyi gönderdiğinizde günlük kayıtlar da işveren tarafından dijital olarak imzalanır.</div><div className="grid gap-4 lg:grid-cols-[1.1fr_1fr]"><Panel title="Günlük kayıtlar">{logs.isLoading ? <LoadingState label="Günlük kayıtlar yükleniyor" /> : logs.isError ? <ErrorState title="Günlük kayıtlar alınamadı" message={normalizeApiError(logs.error).message} onRetry={() => void logs.refetch()} /> : logs.data?.length ? <Table caption="Günlük kayıtlar" columns={[{ key: 'logDate', header: 'Tarih' }, { key: 'content', header: 'İçerik', className: 'whitespace-normal' }]} data={logs.data} rowKey={(row) => row.logDate} /> : <p className="text-sm text-gray-500">Henüz günlük kayıt bulunmuyor.</p>}</Panel><Panel title="Değerlendirme formu"><div className="grid gap-3"><Input label="İşveren adı" value={employerName} onChange={(event) => setEmployerName(event.target.value)} />{employerEvaluationCriteria.map(([key, label]) => <Select key={key} label={label} value={grades[key] ?? ''} onChange={(event) => setGrades({ ...grades, [key]: event.target.value })} options={['A', 'B', 'C', 'D', 'E'].map((letter) => ({ value: letter, label: letter }))} placeholder="Not seçin" />)}<Textarea label="Yorumlar (isteğe bağlı)" value={comments} onChange={(event) => setComments(event.target.value)} /><Button loading={submitState === 'loading'} disabled={!complete || !employerName.trim()} onClick={() => void submit()}>Değerlendirmeyi gönder</Button>{submitState === 'error' ? <p className="text-sm text-red" role="alert">{submitError}</p> : null}</div></Panel></div></main>
}
