import { Link, useParams } from 'react-router-dom'
import { useState } from 'react'
import { Badge, Button, ErrorState, Input, LoadingState, PageHeader, Panel, Textarea } from '../../components/ui'
import { DocumentTitle } from '../../routes/pages'
import { api } from '../../lib/api'
import { useCompanies, useCreateDailyLog, useDailyLogs, useEmployerEvaluation, useFinalGrade, useInternship, useUpdateDailyLog } from './internship.queries'
import { internshipStatusLabels } from './internship.types'
import type { UserRole } from '../auth/auth.types'
import { EmployerEvaluationPanel } from '../academic/components/EmployerEvaluationPanel'
import { groupDailyLogs } from './priority3'
import { canManageEmployerEvaluation, canRoleViewDailyLogs } from './priority5'

export function InternshipDetailPage({ role }: { role: UserRole }) {
  const { id } = useParams<{ id: string }>()
  const detail = useInternship(id)
  const companies = useCompanies(role !== 'ADMINISTRATIVE')
  const logs = useDailyLogs(id, role === 'STUDENT' || Boolean(detail.data && canRoleViewDailyLogs(role, detail.data.status)))
  const evaluation = useEmployerEvaluation(id, role === 'STUDENT' && Boolean(detail.data && ['GRADED', 'COMPLETED'].includes(detail.data.status)))
  const finalGrade = useFinalGrade(id, role === 'STUDENT' && Boolean(detail.data && ['GRADED', 'COMPLETED'].includes(detail.data.status)))
  const [editingLogId, setEditingLogId] = useState<string | null>(null)
  const [logDate, setLogDate] = useState('')
  const [content, setContent] = useState('')
  const [workingDays, setWorkingDays] = useState<number | null>(null)
  const [range, setRange] = useState({ startDate: '', endDate: '' })
  const [selectedLogDate, setSelectedLogDate] = useState('')
  const createLog = useCreateDailyLog(id ?? '')
  const updateLog = useUpdateDailyLog(id ?? '')
  if (detail.isLoading) return <><DocumentTitle title="Staj detayı" /><LoadingState label="Staj detayı yükleniyor" /></>
  if (detail.isError || !detail.data) return <><DocumentTitle title="Staj detayı" /><ErrorState title="Staj bulunamadı" message="Staj bilgileri yüklenirken bir sorun oluştu." onRetry={() => void detail.refetch()} /></>
  const item = detail.data
  const companyName = item.companyName ?? item.company?.name ?? companies.data?.find((company) => company.id === item.companyId)?.name
  const canEditLogs = role === 'STUDENT' && !['EVALUATION', 'GRADED', 'COMPLETED'].includes(item.status)
  const logsDescription = canEditLogs
    ? 'Staj günlerinizi düzenli olarak kaydedin.'
    : ['EVALUATION', 'GRADED', 'COMPLETED'].includes(item.status)
      ? 'Staj tamamlandığı için günlük kayıtlar salt okunurdur.'
      : 'Bu rolde günlük kayıtlar salt okunurdur.'
  const logsRestricted = role === 'ACADEMIC' && !canRoleViewDailyLogs(role, item.status)
  const groupedLogs = groupDailyLogs(logs.data ?? [])
  const activeLogDay = groupedLogs.find((day) => day.date === selectedLogDate) ?? groupedLogs[0]
  return <>
    <DocumentTitle title="Staj detayı" />
    <PageHeader title={companyName ?? 'Staj detayı'} description="Staj başvurusu, belgeler ve günlük kayıtlar." backHref="/internships" backLabel="Staj listesine dön" actions={<div className="flex flex-wrap gap-2"><Link className="rounded-md border border-navy px-3 py-2 text-sm font-semibold text-navy hover:bg-gray-50" to={`/internships/${id}/documents`}>Belgeler</Link><Link className="rounded-md border border-navy px-3 py-2 text-sm font-semibold text-navy hover:bg-gray-50" to={`/internships/${id}/application-form`}>Başvuru formu</Link>{['STUDENT', 'ACADEMIC'].includes(role) && ['EVALUATION', 'GRADED', 'COMPLETED'].includes(item.status) ? <Link className="rounded-md border border-navy px-3 py-2 text-sm font-semibold text-navy hover:bg-gray-50" to={`/internships/${id}/staj-defteri`}>Staj defteri</Link> : null}{role === 'ACADEMIC' && ['EVALUATION', 'GRADED', 'COMPLETED'].includes(item.status) ? <Link className="rounded-md border border-navy px-3 py-2 text-sm font-semibold text-navy hover:bg-gray-50" to={`/internships/${id}/sicil-fisi`}>Sicil fişi</Link> : null}{role === 'ACADEMIC' && item.status === 'EVALUATION' ? <Link className="rounded-md bg-red px-3 py-2 text-sm font-semibold text-white hover:bg-red/90" to={`/scoring/${id}`}>Akademik puan</Link> : null}</div>} />
    <div className="grid gap-4 lg:grid-cols-[1fr_1.5fr]">
      <Panel title="Başvuru özeti"><dl className="grid gap-3 text-sm"><div><dt className="text-xs uppercase tracking-wide text-gray-500">Durum</dt><dd className="mt-1"><Badge variant="info">{internshipStatusLabels[item.status] ?? item.status}</Badge></dd></div><div><dt className="text-xs uppercase tracking-wide text-gray-500">Tarih aralığı</dt><dd className="mt-1 font-semibold text-navy">{item.startDate} — {item.endDate}</dd></div><div><dt className="text-xs uppercase tracking-wide text-gray-500">Kurum</dt><dd className="mt-1">{companyName ?? '—'}</dd></div></dl></Panel>
      <Panel title="Günlük kayıtlar" description={logsDescription}>{logsRestricted ? <p className="rounded border border-gray-200 bg-gray-50 p-4 text-sm text-gray-600" role="status">Günlük kayıtları değerlendirme aşaması başladığında görüntülenebilir.</p> : logs.isLoading ? <LoadingState label="Günlük kayıtlar yükleniyor" /> : logs.isError ? <ErrorState title="Günlük kayıtlar alınamadı" message="Kayıtlar yüklenirken bir sorun oluştu." onRetry={() => void logs.refetch()} /> : groupedLogs.length === 0 ? <div className="rounded border border-dashed border-gray-300 p-4 text-sm text-gray-500">Henüz günlük kayıt eklenmedi.</div> : <><div className="flex flex-wrap gap-2" aria-label="Günlük kayıt tarihleri">{groupedLogs.map((day) => <button key={day.date} type="button" aria-pressed={activeLogDay?.date === day.date} className={`rounded border px-3 py-2 text-sm font-semibold transition ${activeLogDay?.date === day.date ? 'border-navy bg-navy text-white' : 'border-gray-200 text-navy hover:border-red'}`} onClick={() => setSelectedLogDate(day.date)}>{day.date}</button>)}</div>{activeLogDay ? <div className="mt-4 rounded border border-gray-200 bg-gray-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-gray-500">{activeLogDay.date}</p>{activeLogDay.entries.map((entry) => <div key={entry.id} className="mt-3 border-b border-gray-200 pb-3 last:border-0 last:pb-0"><p className="whitespace-pre-wrap text-sm leading-6 text-gray-700">{entry.content}</p>{canEditLogs ? <button type="button" className="mt-2 text-sm font-semibold text-navy underline hover:text-red" onClick={() => { setEditingLogId(entry.id); setLogDate(entry.logDate); setContent(entry.content) }}>Düzenle</button> : null}</div>)}</div> : null}{canEditLogs ? <div className="mt-5 border-t border-gray-200 pt-5"><p className="text-sm font-bold text-navy">{editingLogId ? 'Günlük kaydı düzenle' : 'Yeni günlük kayıt'}</p><div className="mt-3 grid gap-3 sm:grid-cols-[12rem_1fr]"><Input label="Tarih" type="date" value={logDate} onChange={(event) => setLogDate(event.target.value)} /><Textarea label="Gün içeriği" value={content} onChange={(event) => setContent(event.target.value)} /></div><div className="mt-3 flex gap-2"><Button loading={createLog.isPending || updateLog.isPending} onClick={() => { if (editingLogId) void updateLog.mutateAsync({ id: editingLogId, logDate, content }).then(() => { setEditingLogId(null); setLogDate(''); setContent('') }); else void createLog.mutateAsync({ logDate, content }).then(() => { setLogDate(''); setContent('') }) }}>{editingLogId ? 'Kaydı güncelle' : 'Kayıt ekle'}</Button>{editingLogId ? <Button variant="outline" onClick={() => { setEditingLogId(null); setLogDate(''); setContent('') }}>Vazgeç</Button> : null}</div></div> : null}</>}</Panel>
    </div>
    {role === 'STUDENT' ? <Panel className="mt-4" title="Çalışma günü hesapla" description="Staj tarih aralığınız için resmi tatilleri dikkate alarak çalışma gününü hesaplayın."><div className="grid gap-3 sm:grid-cols-[12rem_12rem_auto] sm:items-end"><Input label="Başlangıç" type="date" value={range.startDate} onChange={(event) => setRange({ ...range, startDate: event.target.value })} /><Input label="Bitiş" type="date" value={range.endDate} onChange={(event) => setRange({ ...range, endDate: event.target.value })} /><Button onClick={() => void api.post<{ totalDays: number }>('/holidays/calculate-working-days', { ...range, includeSaturdays: false }).then((response) => setWorkingDays(response.data.totalDays))}>Hesapla</Button></div>{workingDays !== null ? <p className="mt-3 text-sm font-semibold text-navy" role="status">Toplam çalışma günü: {workingDays}</p> : null}</Panel> : null}
    {role === 'STUDENT' && ['GRADED', 'COMPLETED'].includes(item.status) ? <Panel className="mt-4" title="İşveren değerlendirmesi" description="Notlandırma tamamlandığı için sonuçlar salt okunur olarak gösterilir.">{evaluation.isLoading ? <LoadingState label="Değerlendirme yükleniyor" /> : evaluation.isError ? <ErrorState title="Değerlendirme alınamadı" message="Değerlendirme sonucu şu anda görüntülenemiyor." onRetry={() => void evaluation.refetch()} /> : evaluation.data ? <><div className="grid gap-3 sm:grid-cols-2">{Object.entries(evaluation.data.grades).map(([key, value]) => <div key={key} className="flex items-center justify-between border-b border-gray-100 py-2 text-sm"><span className="text-gray-600">{key}</span><Badge variant="success">{value}</Badge></div>)}</div>{evaluation.data.comments ? <p className="mt-4 whitespace-pre-wrap text-sm text-gray-700">{evaluation.data.comments}</p> : null}<p className="mt-3 text-xs text-gray-500">İşveren: {evaluation.data.employerName} · {new Date(evaluation.data.submittedAt).toLocaleDateString('tr-TR')}</p>{evaluation.data.employerLogsApprovedAt ? <p className="mt-3 border-l-4 border-gold bg-gold/10 p-3 text-sm font-semibold text-navy">Günlük kayıtlar işveren tarafından dijital olarak onaylandı · {new Date(evaluation.data.employerLogsApprovedAt).toLocaleString('tr-TR')}</p> : null}</> : null}</Panel> : null}
    {role === 'STUDENT' && ['GRADED', 'COMPLETED'].includes(item.status) ? <Panel className="mt-4" title="Final notu" description="Akademik değerlendirme sonucunuz.">{finalGrade.isLoading ? <LoadingState label="Final notu yükleniyor" /> : finalGrade.isError ? <ErrorState title="Final notu alınamadı" message="Final notu şu anda görüntülenemiyor." onRetry={() => void finalGrade.refetch()} /> : finalGrade.data ? <div className="grid gap-3 sm:grid-cols-4"><div><p className="text-xs uppercase text-gray-500">İşveren</p><p className="mt-1 text-lg font-bold text-navy">{finalGrade.data.employerScore}</p></div><div><p className="text-xs uppercase text-gray-500">Akademik</p><p className="mt-1 text-lg font-bold text-navy">{finalGrade.data.academicScore}</p></div><div><p className="text-xs uppercase text-gray-500">Final</p><p className="mt-1 text-lg font-bold text-navy">{finalGrade.data.finalScore}</p></div><div><p className="text-xs uppercase text-gray-500">Harf</p><p className="mt-1 text-lg font-bold text-red">{finalGrade.data.letterGrade}</p></div></div> : null}</Panel> : null}
    {canManageEmployerEvaluation(role, item.status) ? <EmployerEvaluationPanel internshipId={id ?? ''} /> : null}
  </>
}
