import { useMutation, useQuery } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import { DocumentTitle } from '../../routes/pages'
import { Button, ConfirmDialog, DataToolbar, EmptyState, ErrorState, FileUpload, LoadingState, PageHeader, Panel, Pagination, Select, Table, Textarea } from '../../components/ui'
import { api } from '../../lib/api'
import { queryKeys } from '../../lib/query-keys'
import type { UserRole } from '../auth/auth.types'
import { useTableUrlState } from '../shared/hooks/useTableUrlState'

export interface ApplicationDocument { id: string; documentTypeId?: string; documentType?: { id?: string; name?: string; isRequired?: boolean }; originalFilename?: string; status?: string; versionNumber?: number }
export interface RequiredDocumentType { id: string; name: string; isRequired?: boolean; source?: string }

export function buildDocumentChecklist(types: RequiredDocumentType[], documents: ApplicationDocument[]) {
  return types.filter((type) => type.isRequired && (type.source ?? 'EXTERNAL_UPLOAD') === 'EXTERNAL_UPLOAD').map((type) => {
    const versions = documents.filter((document) => document.documentTypeId === type.id || document.documentType?.id === type.id)
    const latest = [...versions].sort((a, b) => (b.versionNumber ?? 0) - (a.versionNumber ?? 0))[0]
    return { ...type, status: latest?.status ?? 'PENDING', versionNumber: latest?.versionNumber ?? 0 }
  })
}

export function InternshipDocumentsPage({ role = 'STUDENT' }: { role?: UserRole }) {
  const { id } = useParams<{ id: string }>(); const table = useTableUrlState()
  const query = useQuery({ queryKey: [...queryKeys.internships.detail(id ?? ''), 'documents'], queryFn: async () => (await api.get<ApplicationDocument[]>(`/internships/${id}/documents`)).data, enabled: Boolean(id) })
  const documentTypes = useQuery({ queryKey: queryKeys.documentTypes.all, queryFn: async () => (await api.get<RequiredDocumentType[]>('/document-types')).data })
  const [documentTypeId, setDocumentTypeId] = useState(''); const [rejectingId, setRejectingId] = useState<string | null>(null); const [reason, setReason] = useState('')
  const review = useMutation({ mutationFn: ({ documentId, decision, rejectionReason }: { documentId: string; decision: 'accept' | 'reject'; rejectionReason?: string }) => api.post(`/application-documents/${documentId}/${decision}`, decision === 'reject' ? { reason: rejectionReason } : undefined), onSuccess: () => { setRejectingId(null); setReason(''); void query.refetch() } })
  async function upload(file: File) { const formData = new FormData(); formData.append('file', file); formData.append('documentTypeId', documentTypeId); await api.post(`/internships/${id}/documents`, formData); await query.refetch() }
  const rows = query.data ?? []; const filteredRows = useMemo(() => rows.filter((row) => `${row.originalFilename ?? ''} ${row.status ?? ''} ${row.documentType?.name ?? ''}`.toLowerCase().includes(table.search.toLowerCase())).sort((a, b) => table.sort ? String(a[table.sort as keyof ApplicationDocument] ?? '').localeCompare(String(b[table.sort as keyof ApplicationDocument] ?? '')) : 0), [rows, table.search, table.sort]); const totalPages = Math.max(1, Math.ceil(filteredRows.length / table.pageSize)); const pageRows = filteredRows.slice((table.page - 1) * table.pageSize, table.page * table.pageSize)
  const checklist = buildDocumentChecklist(documentTypes.data ?? [], rows); const hasPendingRequired = checklist.some((item) => item.status !== 'ACCEPTED')
  return <><DocumentTitle title="Staj belgeleri" /><PageHeader title="Staj belgeleri" description="Belgelerinizi yükleyin, sürümlerini ve kontrol durumunu izleyin." />
    {role === 'STUDENT' ? <Panel title="Zorunlu belge kontrol listesi" description={hasPendingRequired ? 'Gönderim öncesinde tüm zorunlu belgeler kabul edilmelidir.' : 'Tüm zorunlu belgeler kabul edildi.'}><div className="grid gap-2">{checklist.length === 0 ? <p className="text-sm text-gray-500">Bu staj için zorunlu harici belge tanımlanmamış.</p> : checklist.map((item) => <div key={item.id} className="flex items-center justify-between border-b border-gray-100 py-2 text-sm"><span className="font-medium text-navy">{item.name}</span><span className={item.status === 'ACCEPTED' ? 'text-green-700' : item.status === 'REJECTED' ? 'text-red' : 'text-gray-500'}>{item.status} · v{item.versionNumber}</span></div>)}</div></Panel> : null}
    <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1.5fr]"><Panel title={role === 'STUDENT' ? 'Yeni belge' : 'Belge kontrolü'}>{role === 'STUDENT' ? <><Select label="Belge türü" value={documentTypeId} onChange={(event) => setDocumentTypeId(event.target.value)} options={(documentTypes.data ?? []).map((item) => ({ value: item.id, label: `${item.name}${item.isRequired ? ' · zorunlu' : ''}` }))} /><div className="mt-3"><FileUpload label="Belge dosyası" disabled={!documentTypeId} onFilesSelected={(files) => { const file = files[0]; if (file) void upload(file) }} /></div><p className="mt-3 text-xs text-gray-500">Her yükleme yeni bir versiyon oluşturur.</p></> : <p className="text-sm text-gray-600">Belgeleri kabul edin veya reddedin. Red işlemi için gerekçe zorunludur.</p>}</Panel>
      <Panel title="Yüklenen belgeler"><DataToolbar search={{ value: table.search, onChange: (value) => table.update({ search: value }), placeholder: 'Belge ara' }} filters={<Select label="Sırala" value={table.sort} onChange={(event) => table.update({ sort: event.target.value })} options={[{ value: 'originalFilename', label: 'Dosya' }, { value: 'status', label: 'Durum' }, { value: 'versionNumber', label: 'Versiyon' }]} placeholder="Sıralama" />} />{query.isFetching && !query.isLoading ? <p className="text-xs text-gray-500" role="status">Liste güncelleniyor…</p> : null}<div className="mt-4">{query.isLoading ? <LoadingState label="Belgeler yükleniyor" /> : query.isError ? <ErrorState title="Belgeler alınamadı" message="Belgeler yüklenirken bir sorun oluştu." onRetry={() => void query.refetch()} /> : filteredRows.length === 0 ? <EmptyState title={table.search ? 'Sonuç bulunamadı' : 'Henüz belge yok'} message={table.search ? 'Arama ölçütünü değiştirip tekrar deneyin.' : 'İlk belgenizi yüklediğinizde burada görünecek.'} /> : <><Table caption="Staj belgeleri" columns={[{ key: 'originalFilename', header: 'Dosya' }, { key: 'status', header: 'Durum' }, { key: 'versionNumber', header: 'Versiyon' }, ...(role !== 'STUDENT' ? [{ key: 'review', header: 'İnceleme', render: (row: ApplicationDocument) => <div className="flex gap-2"><Button className="px-2" onClick={() => review.mutate({ documentId: row.id, decision: 'accept' })}>Kabul et</Button><Button variant="danger" className="px-2" onClick={() => { setRejectingId(row.id); setReason('') }}>Reddet</Button></div> }] : [])]} data={pageRows} rowKey={(row) => row.id} /><Pagination className="mt-4 justify-end" page={Math.min(table.page, totalPages)} totalPages={totalPages} onPageChange={(page) => table.update({ page })} /></>}</div></Panel></div>
    <ConfirmDialog open={Boolean(rejectingId)} title="Belgeyi reddet" description="Red gerekçesi başvuru sahibine gösterilir ve zorunludur." confirmLabel="Reddet" onCancel={() => { setRejectingId(null); setReason('') }} onConfirm={() => { if (rejectingId && reason.trim()) review.mutate({ documentId: rejectingId, decision: 'reject', rejectionReason: reason.trim() }) }}><Textarea label="Red gerekçesi" value={reason} onChange={(event) => setReason(event.target.value)} /></ConfirmDialog>
  </>
}
