import { useQuery } from '@tanstack/react-query'
import { DocumentTitle } from '../../routes/pages'
import { Badge, Button, DataToolbar, EmptyState, ErrorState, FileUpload, Input, LoadingState, PageHeader, Panel, Pagination, Select, Table } from '../../components/ui'
import { useState } from 'react'
import { api } from '../../lib/api'
import { queryKeys } from '../../lib/query-keys'
import { useTableUrlState } from '../shared/hooks/useTableUrlState'

export function SgkPage() {
  const query = useQuery({ queryKey: queryKeys.sgk.all, queryFn: async () => (await api.get<Array<Record<string, unknown>>>('/sgk')).data })
  const [internshipId, setInternshipId] = useState(''); const [status, setStatus] = useState('SUBMITTED'); const [message, setMessage] = useState('')
  async function createRecord() { await api.post(`/internships/${internshipId}/sgk`); setMessage('SGK kaydı oluşturuldu.'); await query.refetch() }
  async function updateStatus(id: string) { await api.patch(`/sgk/${id}/status`, { status }); setMessage('SGK durumu güncellendi.'); await query.refetch() }
  async function uploadDocument(id: string, file: File) { const data = new FormData(); data.append('file', file); await api.post(`/sgk/${id}/upload`, data); setMessage('SGK belgesi yüklendi.'); await query.refetch() }
  const table = useTableUrlState(); const rows = (query.data ?? []).filter((row) => Object.values(row).some((value) => String(value ?? '').toLowerCase().includes(table.search.toLowerCase()))); const totalPages = Math.max(1, Math.ceil(rows.length / table.pageSize)); const pageRows = rows.slice((table.page - 1) * table.pageSize, table.page * table.pageSize)
  return <><DocumentTitle title="SGK işlemleri" /><PageHeader title="SGK işlemleri" description="Staj sigorta kayıtlarını ve belge durumlarını bölüm kapsamınızda yönetin." /><Panel className="mb-4" title="SGK kaydı oluştur"><div className="grid gap-3 sm:grid-cols-[1fr_12rem_auto]"><Input label="Staj ID" value={internshipId} onChange={(event) => setInternshipId(event.target.value)} /><Select label="Yeni durum" value={status} onChange={(event) => setStatus(event.target.value)} options={[{ value: 'SUBMITTED', label: 'Gönderildi' }, { value: 'ACTIVE', label: 'Aktif' }]} /><Button onClick={() => void createRecord()}>Kayıt oluştur</Button></div>{message ? <p className="mt-2 text-sm text-navy" role="status">{message}</p> : null}</Panel><Panel><DataToolbar search={{ value: table.search, onChange: (value) => table.update({ search: value }), placeholder: 'Staj veya durum ara' }} /><div className="mt-4">{query.isLoading ? <LoadingState label="SGK kayıtları yükleniyor" /> : query.isError ? <ErrorState title="SGK kayıtları alınamadı" message="Kayıtlar yüklenirken bir sorun oluştu." onRetry={() => void query.refetch()} /> : rows.length === 0 ? <EmptyState title={table.search ? 'Sonuç bulunamadı' : 'SGK kaydı bulunamadı'} message={table.search ? 'Arama ölçütünü değiştirip tekrar deneyin.' : 'Yeni kayıt oluşturulduğunda burada görünecek.'} /> : <><Table caption="SGK kayıtları" columns={[{ key: 'internshipId', header: 'Staj' }, { key: 'status', header: 'Durum', render: (row) => <Badge variant="info">{String(row.status ?? '—')}</Badge> }, { key: 'documentPath', header: 'Belge' }, { key: 'actions', header: 'İşlem', render: (row) => <div className="flex items-center gap-2"><Select label="Durum" value={status} onChange={(event) => { setStatus(event.target.value); void updateStatus(String(row.id)) }} options={[{ value: 'SUBMITTED', label: 'Gönderildi' }, { value: 'ACTIVE', label: 'Aktif' }]} /><FileUpload label="Belge" onFilesSelected={(files) => { const file = files[0]; if (file) void uploadDocument(String(row.id), file) }} /></div> }]} data={pageRows} rowKey={(row) => String(row.id)} /><Pagination className="mt-4 justify-end" page={Math.min(table.page, totalPages)} totalPages={totalPages} onPageChange={(page) => table.update({ page })} /></>}</div></Panel></>
}
